server:
  port: 8082
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webshop
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          infinispan:
            cfg: org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
          region:
            factory_class: infinispan
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: none
    open-in-view: false
  cache:
    infinispan:
      config: classpath:infinispan.xml
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
com:
  csullagrita:
    tokenlib:
      keypaths:
        public: /Users/i554916/tmp/public.pem
#SQL creation with the help of spring JPA
#spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql

