spring:
  application:
    name: order
  config:
    import: optional:configserver:http://localhost:8081
feign:
  product:
    url: http://localhost:8080/catalog

#SQL creation with the help of spring JPA
#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#jms:
#    pub-sub-domain: true